sudo: false
dist: trusty
language: g++
compiler:
- g++
addons:
  apt:
    packages:
    - gcc-mingw-w64-x86-64
    - binutils-mingw-w64-x86-64
    - zip
script:
- '[ -z "$TRAVIS_TAG" ] || SW_VER=-DSW_VER=L\"$TRAVIS_TAG\"'
- 'mkdir out zip'
- 'x86_64-w64-mingw32-dlltool -d wslapi.def -l libwslapi.a'
- 'x86_64-w64-mingw32-gcc -std=c99 --pedantic -Wall -Wno-implicit-function-declaration --static main.c -L./ -lshlwapi -lwslapi -o out/Launcher.exe $SW_VER'
- 'find  ./res/* -maxdepth 1 -type d -printf ''%f\n'' > resl.txt'
- 'xargs -a resl.txt -I{} x86_64-w64-mingw32-windres res/{}/res.rc -o res/{}.o'
- 'xargs -a resl.txt -I{} x86_64-w64-mingw32-gcc -std=c99 --pedantic -Wall -Wno-implicit-function-declaration --static main.c -L./ -lshlwapi -lwslapi res/{}.o -o zip/{}.exe $SW_VER'
- 'cd zip'
- 'zip ../out/icons.zip *'
- 'cd ..'
notifications:
  email: false
#deploy:
#  provider: releases
#  api_key:
#    secure: Y4vr+lcsGVm8rLNI5Ja/e1GwI+9HBCC+29pfRgXJcVaLaYEULgfZDf/h0PoK+mA7B+ooXbivJQkbtCU1mkYpMQq8RywFpk1sTM+BbrpV8Ro2XgEkELmJZ/okYZMh/YH5xee970uc3WczGAHswg+erP7Cju1JPdYh+0uU7rDZ1OeTTJvV1qECijyOtM5Xaa6yXYYx9lK6EK+Prk9k5l/T6grY0bo5MKvuGx1Y0CC7D6YirVy9qnsm7DqFnCSlaTHQ+Hp/MQ1QnQuB0DERw0K6NANtYoLBYtYUf37UmYgdpkryYpVJByqIvd962cv0/qz0KqDDxDrI4GLcRc1LwJm265IhhoSD3QLLgTfrFQ8KHmXbm7bXTkaeaY3j1qPvBE9MzKWtTuAIsw6y8dnBLCfurhGTDESXNbRmB6RAJfF3OTTxdN6r4lcZnEjNbj5sds1BrgvJ5THvrOlAFbjzlUSxkDaLo7We9CCGPV/LrYi6dp1wAFhwphY7Y8D6qAsGQYB4WdNtSLTDPiRIsDske7oez9S3x9iRkUGzYm8wIUW4ki6x/aWRFq+AFx06uMYFtESzNLCinqj3JiC6dbMEe51rKX1U8Nx3oC2mxI3mmohP5LZYt9HNuu2O3wRwKwkB6yoJsKfU5WlF6DFjeIAuSlZDpeiJlXifOOOUbKAxI/+cRfc=
#  file_glob: true
#  file: 'out/*.{exe,zip}'
#  on:
#    repo: yuk7/wsldl
#    tags: true
#    all_branches: true
#  skip_cleanup: true
